// generated-lines.ts — which lines of a file a generator wrote, read from .claude/data/generated-files.tsv.

import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { dataRows } from '../data-rows.ts';
import { globMatches } from './glob-matches.ts';

const scopes = Object.freeze({ head: 'head', block: 'block' } as const);

/**
 * Returns a judge that marks, per line of a file, whether a generator wrote it. A `head` row marks the whole file; a
 * `block` row marks from the line "generated by <generator>" through the next line that closes with `END … -->`.
 * Without the data file nothing is generated.
 */
export function generatedLines(root: string): (path: string, lines: readonly string[]) => boolean[] {
	const data = join(root, '.claude', 'data', 'generated-files.tsv');
	const rows = existsSync(data) ? dataRows(data, 'output').map(({ cells }) => cells) : [];
	return (path, lines) => {
		const marked = lines.map(() => false);
		for (const [output = '', generator = '', scope = ''] of rows) {
			if (!globMatches(path, output)) continue;
			if (scope === scopes.head) return lines.map(() => true);
			if (scope !== scopes.block) continue;
			const marker = `generated by ${(generator.split('/').pop() ?? '').replace(/\.ts$/, '')}`;
			let inside = false;
			lines.forEach((line, index) => {
				if (line.includes(marker)) inside = true;
				if (inside) marked[index] = true;
				if (inside && /\bEND\b.*-->/.test(line)) inside = false;
			});
		}
		return marked;
	};
}
