// check-generated.ts — rejects a generated file that does not name its generator, and a generator without a row in
// .claude/data/generated-files.tsv. Usage: node scripts/check-generated.ts [--all]

import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { dataRows } from './lib/data-rows.ts';

const root = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim();
const table = join(root, '.claude', 'data', 'generated-files.tsv');
const findings: string[] = [];
const rows = existsSync(table) ? dataRows(table, 'output').map(({ cells }) => cells) : [];
if (!existsSync(table)) findings.push('.claude/data/generated-files.tsv is missing');

function expand(pattern: string): string[] {
	if (!pattern.includes('*')) return existsSync(join(root, pattern)) ? [pattern] : [];
	const dir = pattern.slice(0, pattern.lastIndexOf('/'));
	const name = new RegExp(`^${pattern.slice(dir.length + 1).replace(/\./g, '\\.').replace(/\*/g, '.*')}$`);
	return existsSync(join(root, dir)) ? readdirSync(join(root, dir)).filter((file) => name.test(file)).map((file) => `${dir}/${file}`) : [];
}

let files = 0;
for (const [output = '', generator = '', scope = ''] of rows) {
	const hits = expand(output);
	if (hits.length === 0) findings.push(`${output}: listed in generated-files.tsv, but nothing exists there`);
	if (!existsSync(join(root, generator))) findings.push(`${generator}: listed as a generator, but it does not exist`);
	for (const path of hits) {
		files += 1;
		const text = readFileSync(join(root, path), 'utf8');
		const where = scope === 'head' ? text.split('\n').slice(0, 5).join('\n') : text;
		if (!where.includes(`generated by ${generator}`)) {
			findings.push(`${path}: ${scope === 'head' ? 'its first five lines do not' : 'its block does not'} name "generated by ${generator}"`);
		}
	}
}
const listed = new Set(rows.map(([, generator]) => generator));
for (const name of readdirSync(join(root, 'scripts')).filter((file) => /^generate-.+\.ts$/.test(file))) {
	if (!listed.has(`scripts/${name}`)) findings.push(`scripts/${name} has no row in .claude/data/generated-files.tsv`);
}
for (const finding of findings) console.log(`⛔ ${finding}`);
if (findings.length > 0) process.exit(1);
console.log(`✅ check-generated: ${listed.size} generators, ${files} generated files, each names its generator`);
