// generate-adr-state.ts — writes the state table of every ADR from its frontmatter, with the cards whose plans name
// it. Usage: node scripts/generate-adr-state.ts [--check]; with --check it changes nothing and exits 1 on a stale one.

import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parseFrontmatter, type FrontmatterValue } from './lib/frontmatter.ts';

const root = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim();
const begin = '<!-- STATE:BEGIN — generated by scripts/generate-adr-state.ts from the frontmatter; never edit by hand. -->';
const block = /<!-- STATE:BEGIN[\s\S]*?<!-- STATE:END -->/;
const recordDir = join(root, 'docs', 'ADR');
const planDir = join(root, 'docs', 'plans', 'impl');
const records = readdirSync(recordDir).filter((name) => /^\d{4}-.*\.md$/.test(name)).sort();
const plans = (existsSync(planDir) ? readdirSync(planDir) : [])
	.filter((name) => /^PLAN_PIX-\d+_.*\.md$/.test(name))
	.map((name) => ({ card: /PIX-\d+/.exec(name)?.[0] ?? '', text: readFileSync(join(planDir, name), 'utf8') }));

function values(value: FrontmatterValue | undefined): string[] {
	const list = Array.isArray(value) ? value : typeof value === 'string' ? value.replace(/^\[|\]$/g, '').split(/,\s*/) : [];
	return list.map((entry) => entry.trim()).filter((entry) => entry !== '' && entry !== '—' && entry !== 'null');
}

function recordLink(number: string): string {
	const file = records.find((name) => name.startsWith(`${number.padStart(4, '0')}-`));
	return file ? `[${number.padStart(4, '0')}](${file})` : number.padStart(4, '0');
}

function table(name: string, text: string): string {
	const { data } = parseFrontmatter(text);
	const one = (key: string): string => values(data[key])[0] ?? '—';
	const paths = (key: string): string => values(data[key]).map((path) => `[${path.split('/').pop()}](${path.replace(/^docs\//, '../')})`).join(' · ') || '—';
	const number = name.slice(0, 4);
	// A comment behind supersedes or superseded-by narrows it, e.g. to one point; the table carries it along.
	const note = (key: string): string => {
		const comment = new RegExp(`^${key}:[^\\n#]*#\\s*(.+)$`, 'm').exec(text.split('\n---')[0] ?? '')?.[1];
		return comment ? ` (${comment.trim()})` : '';
	};
	const cards = [...new Set(plans.filter((plan) => new RegExp(`ADR ${number}(?!\\d)|ADR/${name}`).test(plan.text)).map((plan) => plan.card))];
	const rows: Array<[string, string]> = [
		['**Status**', one('status')],
		['**Date**', one('date')],
		['**Kind**', one('kind')],
		['**Decision-makers**', one('decision-makers')],
		['**Supersedes**', (values(data['supersedes']).map(recordLink).join(' · ') || '—') + (values(data['supersedes']).length ? note('supersedes') : '')],
		['**Superseded by**', (values(data['superseded-by']).map(recordLink).join(' · ') || '—') + (values(data['superseded-by']).length ? note('superseded-by') : '')],
		['**Analysis**', paths('analysis')],
		['**Implementation**', paths('implementation')],
		['**Cards**', cards.sort((a, b) => Number(a.slice(4)) - Number(b.slice(4))).join(' · ') || '—'],
	];
	const left = Math.max(...rows.map(([label]) => label.length));
	const right = Math.max(...rows.map(([, value]) => value.length));
	const line = (a: string, b: string): string => `| ${a.padEnd(left)} | ${b.padEnd(right)} |`;
	return [begin, '', line('', ''), `| ${'-'.repeat(left)} | ${'-'.repeat(right)} |`, ...rows.map(([a, b]) => line(a, b)), '', '<!-- STATE:END -->'].join('\n');
}

const check = process.argv.includes('--check');
let stale = 0;
for (const name of records) {
	const path = join(recordDir, name);
	const text = readFileSync(path, 'utf8');
	const found = block.exec(text);
	if (!found) {
		console.log(`⛔ docs/ADR/${name} has no STATE:BEGIN … STATE:END block`);
		stale += 1;
		continue;
	}
	const next = text.replace(found[0], table(name, text));
	if (next === text) continue;
	if (check) {
		console.log(`⛔ docs/ADR/${name}: the state table is not generated from its frontmatter and the plans naming it`);
		stale += 1;
	} else {
		writeFileSync(path, next);
	}
}
if (check && stale > 0) {
	console.log('   Fix: node scripts/generate-adr-state.ts');
	process.exit(1);
}
console.log(`${check ? '✅ adr state' : 'adr state written'}: ${records.length} state tables`);
