// generate-skills-index.ts — writes .claude/SKILLS.md from the frontmatter of every skill; --check is the diff gate.
// Usage: node scripts/generate-skills-index.ts [--check]; with --check it changes nothing and exits 1 on a difference.

import { execFileSync } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parseFrontmatter } from './lib/frontmatter.ts';

const root = execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim();
const skillsDir = join(root, '.claude', 'skills');
const target = join(root, '.claude', 'SKILLS.md');

const skills = (existsSync(skillsDir) ? readdirSync(skillsDir).sort() : [])
	.filter((name) => existsSync(join(skillsDir, name, 'SKILL.md')))
	.map((name) => {
		const { data } = parseFrontmatter(readFileSync(join(skillsDir, name, 'SKILL.md'), 'utf8'));
		const description = typeof data['description'] === 'string' ? data['description'] : '';
		const maintainerOnly = data['disable-model-invocation'] === 'true';
		return { name, description: description.replace(/\s+/g, ' ').replace(/\|/g, '\\|').trim(), maintainerOnly };
	});

const wanted = [
	'<!-- generated by scripts/generate-skills-index.ts from the frontmatter of every skill; never edit by hand. -->',
	'',
	'# Skills',
	'',
	'Which skill serves which task. What triggers a skill stands in its `description`, and only there; this table is',
	'its copy for reading. Skills marked "maintainer" are typed by the maintainer and never started by the model.',
	'',
	'| Skill | What it does | Started by |',
	'| --- | --- | --- |',
	...skills.map((skill) => `| [${skill.name}](skills/${skill.name}/SKILL.md) | ${skill.description} | ${skill.maintainerOnly ? 'maintainer' : 'model'} |`),
	'',
].join('\n');

const current = existsSync(target) ? readFileSync(target, 'utf8') : '';
if (process.argv.includes('--check')) {
	if (current === wanted) {
		console.log(`✅ skills index: .claude/SKILLS.md matches ${skills.length} skills`);
		process.exit(0);
	}
	console.log('⛔ .claude/SKILLS.md differs from its generation; it is generated, not maintained.');
	console.log('   Fix: node scripts/generate-skills-index.ts');
	process.exit(1);
}
if (current !== wanted) writeFileSync(target, wanted);
console.log(`.claude/SKILLS.md ${current === wanted ? 'was current' : 'written'} (${skills.length} skills)`);
