#!/usr/bin/env bash
# install-git-hooks.sh — installs the main lock into the shared .git directory, which belongs to no branch, and points
# core.hooksPath at it. Every client hook gets a forwarder: a hook without a file there silently stops running.
set -e -u -o pipefail

git rev-parse --git-dir >/dev/null 2>&1 || {
	echo "⛔ install-git-hooks: not a git repository; the history guard is NOT installed." >&2
	exit 1
}
target="$(git rev-parse --path-format=absolute --git-common-dir)/hooks-active"
mkdir -p "$target"

cat >"$target/pre-commit" <<'HOOK'
#!/usr/bin/env bash
# Generated by scripts/install-git-hooks.sh. Rejects a commit on main, master or a detached HEAD, then forwards.
set -uo pipefail
branch="$(git symbolic-ref --quiet --short HEAD 2>/dev/null || true)"
case "$branch" in
"" | main | master)
	echo "⛔ Commit on '${branch:-detached HEAD}' rejected. Work goes on feat/pix-NNN-short and reaches main through a pull request." >&2
	exit 1
	;;
esac
root="$(git rev-parse --show-toplevel)"
[ -x "$root/.githooks/pre-commit" ] && exec "$root/.githooks/pre-commit" "$@"
exit 0
HOOK

cat >"$target/pre-push" <<'HOOK'
#!/usr/bin/env bash
# Generated by scripts/install-git-hooks.sh. Rejects a push that moves main or master, and a push from a Claude session
# without the maintainer's push window, then forwards. Only the target ref counts, so HEAD:main and deletes are covered.
set -uo pipefail
payload="$(cat)"
while read -r _ _ remote_ref _; do
	case "${remote_ref:-}" in
	refs/heads/main | refs/heads/master)
		echo "⛔ Push to '${remote_ref#refs/heads/}' rejected. Work reaches main through a pull request the maintainer merges." >&2
		exit 1
		;;
	esac
done <<<"$payload"
root="$(git rev-parse --show-toplevel)"
# CLAUDE_CODE_SESSION_ID is set when the push comes from a session; the maintainer opens the window with /push.
if [ -n "${CLAUDE_CODE_SESSION_ID:-}" ] &&
	! node "$root/scripts/ticket.ts" push-allowed "$CLAUDE_CODE_SESSION_ID" >/dev/null 2>&1; then
	echo "⛔ Push from a Claude session without the maintainer's push window rejected. The maintainer types /push [duration]." >&2
	exit 1
fi
[ -x "$root/.githooks/pre-push" ] || exit 0
printf '%s\n' "$payload" | "$root/.githooks/pre-push" "$@"
HOOK

for hook in applypatch-msg pre-applypatch post-applypatch pre-merge-commit prepare-commit-msg commit-msg post-commit \
	pre-rebase post-checkout post-merge post-rewrite; do
	cat >"$target/$hook" <<'HOOK'
#!/usr/bin/env bash
# Generated by scripts/install-git-hooks.sh. Forwards to the versioned hook of the same name when it exists.
root="$(git rev-parse --show-toplevel)"
hook="$root/.githooks/$(basename "$0")"
[ -x "$hook" ] && exec "$hook" "$@"
exit 0
HOOK
done
chmod +x "$target"/*

git config core.hooksPath "$target"
echo "✅ History guard active: $target (main locked, .githooks run behind it)"
