#!/usr/bin/env bash
# probe-find-references.sh — every distinction of find-references once found and once not, on planted files in a
# throwaway repo: carrier, spelling, comment, prose, glob, generated, settings, --self and the exit codes.
set -uo pipefail

root="$(git rev-parse --show-toplevel 2>/dev/null || true)"
[ -n "$root" ] || { echo "probe-find-references.sh: not a git repository." >&2; exit 1; }

# shellcheck source=scripts/lib/probe.sh
source "$root/scripts/lib/probe.sh"
probe_tree_init find-references
# The user's own settings are read too; a home of its own keeps the real one out of every case.
probe_env() { export HOME="$work/home"; }

mkdir -p "$work/scripts/lib/shell" "$work/.claude/rules" "$work/.claude/data" "$work/.claude/hooks" "$work/docs"
cp "$root/scripts/find-references.ts" "$work/scripts/"
cp -R "$root/scripts/lib/references" "$root/scripts/lib/comments" "$root/scripts/lib/data-rows.ts" "$work/scripts/lib/"
cp "$root/scripts/lib/shell/command-lexer.ts" "$work/scripts/lib/shell/"

cd "$work" || exit 1
printf '%s\n' '# Area' '' '## Every target is checked `[Gate probe-target]`' >.claude/rules/area.md
echo 'export const target = 1;' >scripts/probe-target.ts
cat >scripts/caller.ts <<'FIXTURE'
// Mentions probe-target.ts only in a comment.
import { target } from './probe-target.ts';
console.log('⛔ probe-message.ts failed, run it again');
execFileSync('node', ['scripts/probe-message.ts']);
const a = 1; /* probe-tail.ts in a block */
run('probe-tail.ts');
const quote = /'/; log('see probe-regex.ts');
const help = `
	runs probe-template.ts for you
	node scripts/probe-template.ts --fast
`;
FIXTURE
cat >scripts/caller.sh <<'FIXTURE'
#!/usr/bin/env bash
# names probe-shell.sh in a comment
bash scripts/probe-shell.sh
echo "probe-shell.sh is gone"
set -u # trailing probe-shell.sh
cat <<EOF
probe-shell.sh in a heredoc
EOF
out="$(bash scripts/probe-shell.sh)"
FIXTURE
printf '#!/usr/bin/env bash\necho ok\n' >scripts/probe-glob-target.sh
cat >scripts/runner.sh <<'FIXTURE'
#!/usr/bin/env bash
for f in scripts/probe-glob*.sh; do bash "$f"; done
for f in scripts/*.sh; do :; done
# every scripts/probe-glob*.sh runs here
for f in scripts/**/probe-glob*.sh; do :; done
FIXTURE
printf '%s\n' '{"permissions":{"allow":["Bash(.claude/hooks/probe-perm.ts:*)"]},' \
	'"hooks":{"Stop":[{"hooks":[{"type":"command","command":"node .claude/hooks/probe-event.ts"}]}]}}' \
	>.claude/settings.json
printf 'file\tnote\nprobe-data.ts\tread here\n' >.claude/data/list.tsv
printf '%s\n' 'output	generator	scope' 'docs/generated.md	scripts/generate-index.ts	head' \
	'docs/state-*.md	scripts/generate-state.ts	block' >.claude/data/generated-files.tsv
printf '%s\n' '<!-- generated by generate-index -->' 'probe-gen.ts listed' >docs/generated.md
echo 'probe-gen.ts is described here' >docs/manual.md
printf '%s\n' '# State' 'probe-block.ts before' '<!-- STATE:BEGIN — generated by generate-state -->' \
	'probe-block.ts inside' '<!-- STATE:END -->' 'probe-block.ts after' >docs/state-one.md
cd "$root" || exit 1
probe_tree_commit

T=$'\t'
refs='node scripts/find-references.ts'
has() {
	local pattern="$1"
	shift
	node scripts/find-references.ts "$@" | grep -qE "$pattern"
}

echo "── Carriers and spellings ──────────────────────────────────────────────"
probe "a rule names the file without its extension" green \
	"has '^RULE${T}.claude/rules/area.md:3${T}no-extension${T}' probe-target.ts"
probe "  twin: a shorter name does not run into the word" red "has '^RULE${T}' probe-tar.ts"
probe "a data file is DATA" green "has '^DATA${T}.claude/data/list.tsv:2${T}' probe-data.ts"
probe "  twin: a doc is no DATA" red "has '^DATA${T}' probe-gen.ts"
probe "a hook command in settings is EVENT" green "has '^EVENT${T}.claude/settings.json:2${T}' probe-event.ts"
probe "  twin: a permission entry is no EVENT" red "has '^EVENT${T}' probe-perm.ts"
probe "  twin: a sibling with another extension is not found" red "has 'settings' probe-event.js"
probe "the user's settings are read" green \
	"mkdir -p home/.claude && cp .claude/settings.json home/.claude/
	 has '^EVENT${T}~/.claude/settings.json:2${T}' probe-event.ts"
probe "  twin: without them nothing from home" red "has '~/.claude/settings.json' probe-event.ts"

echo
echo "── TypeScript: comment, code and prose ─────────────────────────────────"
probe "a line comment is COMMENT" green "has '^SCRIPT COMMENT${T}scripts/caller.ts:1${T}' probe-target.ts"
probe "  twin: the import is code" red "has '^SCRIPT (COMMENT|TEXT)${T}scripts/caller.ts:2${T}' probe-target.ts"
probe "prose in a string is TEXT" green "has '^SCRIPT TEXT${T}scripts/caller.ts:3${T}' probe-message.ts"
probe "  twin: a path argument is code" red "has '^SCRIPT (COMMENT|TEXT)${T}scripts/caller.ts:4${T}' probe-message.ts"
probe "a block comment after code is COMMENT" green "has '^SCRIPT COMMENT${T}scripts/caller.ts:5${T}' probe-tail.ts"
probe "  twin: the call after it is code" red "has '^SCRIPT (COMMENT|TEXT)${T}scripts/caller.ts:6${T}' probe-tail.ts"
probe "a quote inside a regex opens no string" green "has '^SCRIPT TEXT${T}scripts/caller.ts:7${T}' probe-regex.ts"
probe "prose in a template literal is TEXT" green "has '^SCRIPT TEXT${T}scripts/caller.ts:9${T}' probe-template.ts"
probe "  twin: a command in it is code" red "has '^SCRIPT (COMMENT|TEXT)${T}scripts/caller.ts:10${T}' probe-template.ts"

echo
echo "── Shell: comment, call and mention ────────────────────────────────────"
probe "a shell comment is COMMENT" green "has '^SCRIPT COMMENT${T}scripts/caller.sh:2${T}' probe-shell.sh"
probe "  twin: a call is code" red "has '^SCRIPT (COMMENT|TEXT)${T}scripts/caller.sh:3${T}' probe-shell.sh"
probe "echo is TEXT" green "has '^SCRIPT TEXT${T}scripts/caller.sh:4${T}' probe-shell.sh"
probe "a comment after code is COMMENT" green "has '^SCRIPT COMMENT${T}scripts/caller.sh:5${T}' probe-shell.sh"
probe "a heredoc body is TEXT" green "has '^SCRIPT TEXT${T}scripts/caller.sh:7${T}' probe-shell.sh"
probe "  twin: a call in \$( … ) is code" red "has '^SCRIPT (COMMENT|TEXT)${T}scripts/caller.sh:9${T}' probe-shell.sh"

echo
echo "── Globs: a loop that runs the file without naming it ──────────────────"
probe "a glob in a loop is SCRIPT GLOB" green "has '^SCRIPT GLOB${T}scripts/runner.sh:2${T}' probe-glob-target.sh"
probe "  twin: a glob that selects every file does not count" red "has 'scripts/runner.sh:3${T}' probe-glob-target.sh"
probe "a glob in a comment is SCRIPT GLOB COMMENT" green \
	"has '^SCRIPT GLOB COMMENT${T}scripts/runner.sh:4${T}' probe-glob-target.sh"
probe "a glob with a double star is SCRIPT GLOB" green \
	"has '^SCRIPT GLOB${T}scripts/runner.sh:5${T}' probe-glob-target.sh"
probe "  twin: a glob that misses the file does not count" red "has '^SCRIPT GLOB' probe-target.ts"

echo
echo "── Generated files ─────────────────────────────────────────────────────"
probe "a file a generator writes is GENERATED" green "has '^DOC GENERATED${T}docs/generated.md:2${T}' probe-gen.ts"
probe "  twin: a hand-written doc is not" red "has '^DOC GENERATED${T}docs/manual.md' probe-gen.ts"
probe "a line inside a generated block is GENERATED" green \
	"has '^DOC GENERATED${T}docs/state-one.md:4${T}' probe-block.ts"
probe "  twin: the lines around the block are not" red \
	"has '^DOC GENERATED${T}docs/state-one.md:(2|6)${T}' probe-block.ts"

echo
echo "── --self and the exit codes ───────────────────────────────────────────"
probe "--self from the root leaves the file out" red "has 'scripts/caller.ts:' probe-target.ts --self scripts/caller.ts"
probe "  twin: without --self it is in" green "has 'scripts/caller.ts:' probe-target.ts"
probe "--self with an absolute path" red "has 'scripts/caller.ts:' probe-target.ts --self \$PWD/scripts/caller.ts"
probe "--self relative to the caller goes first" red \
	"cd scripts && node find-references.ts probe-target.ts --self caller.ts | grep -q 'scripts/caller.ts:'"
probe "--self from the root works from a subdirectory" red \
	"cd scripts && node find-references.ts probe-target.ts --self scripts/caller.ts | grep -q 'scripts/caller.ts:'"
probe "--self without a value is a wrong call, exit 2" green "$refs probe-target.ts --self; [ \$? -eq 2 ]"
probe "no term at all is a wrong call, exit 2" green "$refs; [ \$? -eq 2 ]"
probe "a term named nowhere ends with exit 1" green "$refs no-such-term-anywhere; [ \$? -eq 1 ]"
probe "  twin: a term named somewhere ends with exit 0" green "$refs probe-target.ts"
probe "several terms, one named nowhere: exit 1 with its heading" green \
	"$refs probe-target.ts no-such-term-anywhere > out; [ \$? -eq 1 ] && grep -q '^== no-such-term-anywhere: named' out"
probe "  twin: several terms all named: exit 0" green "$refs probe-target.ts probe-gen.ts"

echo
probe_done
